import React from 'react';

export interface SeedWizardProps {
  step: any;
  setStep: React.Dispatch<React.SetStateAction<any>>;
  connectionMode: 'string' | 'fields';
  setConnectionMode: React.Dispatch<React.SetStateAction<'string' | 'fields'>>;
  connectionString: any;
  setConnectionString: React.Dispatch<React.SetStateAction<any>>;
  dbConfig: any;
  setDbConfig: React.Dispatch<React.SetStateAction<any>>;
  schema: any;
  setSchema: React.Dispatch<React.SetStateAction<any>>;
  connecting: any;
  setConnecting: React.Dispatch<React.SetStateAction<any>>;
  dbError: any;
  setDbError: React.Dispatch<React.SetStateAction<any>>;
  tables: string[];
  setTables: React.Dispatch<React.SetStateAction<string[]>>;
  selectedTable: any;
  setSelectedTable: React.Dispatch<React.SetStateAction<any>>;
  manualTable: any;
  setManualTable: React.Dispatch<React.SetStateAction<any>>;
  columns: any[];
  setColumns: React.Dispatch<React.SetStateAction<any[]>>;
  fetchingCols: any;
  setFetchingCols: React.Dispatch<React.SetStateAction<any>>;
  loadingData: any;
  setLoadingData: React.Dispatch<React.SetStateAction<any>>;
  fkOptions: Record<string, any[]>;
  setFkOptions: React.Dispatch<React.SetStateAction<Record<string, any[]>>>;
  csvFile: File | null;
  setCsvFile: React.Dispatch<React.SetStateAction<File | null>>;
  csvHeaders: string[];
  setCsvHeaders: React.Dispatch<React.SetStateAction<string[]>>;
  csvData: any[];
  setCsvData: React.Dispatch<React.SetStateAction<any[]>>;
  editorPage: any;
  setEditorPage: React.Dispatch<React.SetStateAction<any>>;
  validationErrors: Record<number, Record<string, string>>;
  setValidationErrors: React.Dispatch<React.SetStateAction<Record<number, Record<string, string>>>>;
  editingRowIdx: number | null;
  setEditingRowIdx: React.Dispatch<React.SetStateAction<number | null>>;
  editFormData: any;
  setEditFormData: React.Dispatch<React.SetStateAction<any>>;
  mapping: Record<string, string>;
  setMapping: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  generateUuidFor: Record<string, boolean>;
  setGenerateUuidFor: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  exportedJson: any;
  setExportedJson: React.Dispatch<React.SetStateAction<any>>;
  exportedSql: any;
  setExportedSql: React.Dispatch<React.SetStateAction<any>>;
  executing: any;
  setExecuting: React.Dispatch<React.SetStateAction<any>>;
  executeResult: any;
  setExecuteResult: React.Dispatch<React.SetStateAction<any>>;
  wizardMode: 'csv' | 'entity';
  setWizardMode: React.Dispatch<React.SetStateAction<'csv' | 'entity'>>;
  entityDirPath: any;
  setEntityDirPath: React.Dispatch<React.SetStateAction<any>>;
  entities: any[];
  setEntities: React.Dispatch<React.SetStateAction<any[]>>;
  scanningEntities: any;
  setScanningEntities: React.Dispatch<React.SetStateAction<any>>;
  entityError: any;
  setEntityError: React.Dispatch<React.SetStateAction<any>>;
  selectedRootEntity: any;
  setSelectedRootEntity: React.Dispatch<React.SetStateAction<any>>;
  entityFormDataList: any[];
  setEntityFormDataList: React.Dispatch<React.SetStateAction<any[]>>;
  activeRecordIndex: number | null;
  setActiveRecordIndex: React.Dispatch<React.SetStateAction<number | null>>;
  activeRecordData: any;
  setActiveRecordData: React.Dispatch<React.SetStateAction<any>>;
  scanSummary: Record<number, string[]> | null;
  setScanSummary: React.Dispatch<React.SetStateAction<Record<number, string[]> | null>>;
  templates: {name: string, sizeKb: string}[];
  setTemplates: React.Dispatch<React.SetStateAction<{name: string, sizeKb: string}[]>>;
  loadingTemplates: any;
  setLoadingTemplates: React.Dispatch<React.SetStateAction<any>>;
  fetchTemplates: (...args: any[]) => any;
  scanEntities: (...args: any[]) => any;
  handleTemplateSelect: (...args: any[]) => any;
  handleConnect: (...args: any[]) => any;
  fetchColumnsForTable: (...args: any[]) => any;
  handleSelectChange: (...args: any[]) => any;
  loadExistingData: (...args: any[]) => any;
  handleFileUpload: (...args: any[]) => any;
  goToMapping: (...args: any[]) => any;
  generateUuidV4: (...args: any[]) => any;
  performEntityExport: (...args: any[]) => any;
  performExport: (...args: any[]) => any;
  handleExecuteSql: (...args: any[]) => any;
  calculateJoinDepths: (...args: any[]) => any;
}
